name: just_audio
description: A feature-rich audio player for Flutter. Loop, clip and concatenate any sound from any source (asset/file/URL/stream) in a variety of audio formats with gapless playback.
version: 0.9.40
repository: https://github.com/Princeyyyy/just_audio/tree/minor/just_audio
issue_tracker: https://github.com/ryanheise/just_audio/issues
topics:
  - audio
  - sound
  - player
  - background

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  just_audio_platform_interface: ^4.3.0
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  just_audio_web: ^0.4.11
  # just_audio_web:
  #   path: ../just_audio_web
  audio_session: ^0.1.21
  rxdart: '>=0.26.0 <0.29.0'
  path: ^1.9.0
  path_provider: ^2.1.4
  async: ^2.11.0
  uuid: '>=3.0.1 <5.0.0'
  crypto: ^3.0.4
  meta: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        default_package: just_audio_web
