name: just_audio_web
description: Web platform implementation of just_audio. This implementation is endorsed and therefore doesn't require a direct dependency.
homepage: https://github.com/Princeyyyy/just_audio/tree/minor/just_audio_web
version: 0.4.11

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JustAudioPlugin
        fileName: just_audio_web.dart

dependencies:
  just_audio_platform_interface:
    path: ../just_audio_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: '>=0.3.0 <1.0.0'

dev_dependencies:
  flutter_lints: ^4.0.0

environment:
  sdk: ^3.2.1
  flutter: '>=3.16.0'